### ISSUE TITLE
Not able to run docker with option -gpu all

### ISSUE THREAD

**Issue by HamzaOuajhain** [HyeonJaeGil/dockerfile-hub#2]
I have downloaded and installed docker.desktop

![Screenshot from 2024-01-03 18-12-59](https://github.com/HyeonJaeGil/DockerSLAM/assets/121122945/5ab40d57-76fd-4a70-8624-a34055fc0c41)

I am not able to run docker run command with gpu option.

docker run -it 6cf6bf3646fd

Also, after being able to access the Docker image, what should I do exactly ? excuse my ignorance

**Comment by HyeonJaeGil** [comment]
Hi, sorry for the late reply.

I have not seen the error you mentioned before,
but you may check if nvidia-docker is successfully installed.
